"""empty message

Revision ID: 0eb63a88f91e
Revises: 4a4616922dab
Create Date: 2023-12-19 17:29:58.318238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb63a88f91e'
down_revision = '4a4616922dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creator', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool')
    # ### end Alembic commands ###
